[dev]
    command = "yarn start"
    port = 8888
    targetPort = 3000
    framework = "#custom"

[build]
    command = "yarn build"
    functions = "functions"
    publish = "build"
    environment = { SEED = "true", NODE_VERSION = "12" }

[context.production]
    environment = { SEED = "false", NODE_VERSION = "12" }
